# ── Luca Schmidt (Grenzebach) ─────────────────────────────────────────────────
[[profiles]]
name = "luca"

[profiles.colors]
primary      = "#ED1B24"
text         = "#000000"
link         = "$colors.primary"
rule         = "$colors.primary"
quote_border = "$colors.primary"

[profiles.sizes]
top_margin  = "3cm"
head_height = "1.3cm"
logo_height = "1cm"

[profiles.identity]
display_name = "Luca Schmidt (GBSH)"
author       = "Luca Michael Schmidt"
institute    = "Grenzebach BSH GmbH | HS Fulda"
email        = "Luca.Schmidt@grenzebach.com"

[profiles.layout]
logo = "assets/gb-logo.png"

# ── HS Fulda (generisch) ──────────────────────────────────────────────────────
[[profiles]]
name = "hs-fulda"

[profiles.colors]
primary      = "#61BD1A"
text         = "#000000"
link         = "$colors.primary"
rule         = "$colors.primary"
quote_border = "$colors.primary"

[profiles.sizes]
top_margin  = "3cm"
head_height = "1.3cm"
logo_height = "1cm"

[profiles.identity]
display_name = "Hochschule Fulda"
institute = "Hochschule Fulda"

[profiles.layout]
logo = "assets/hs-fulda-logo.png"
